import type {
  User,
  Wallet,
  Transaction,
  CryptoAsset,
  CryptoWallet,
  Restaurant,
  MenuItem,
  Badge,
  Mission,
  LeaderboardEntry,
  PulsaProvider,
  PulsaPackage,
  Promo,
  Notification,
  LevelConfig,
} from "./types"

// Level Configuration
export const LEVEL_CONFIGS: LevelConfig[] = [
  {
    name: "bronze",
    displayName: "Bronze",
    minPoints: 0,
    cashbackPercentage: 0.5,
    dailyLimit: 5000000,
    color: "#CD7F32",
    icon: "🥉",
  },
  {
    name: "silver",
    displayName: "Silver",
    minPoints: 5000,
    cashbackPercentage: 1,
    dailyLimit: 10000000,
    color: "#C0C0C0",
    icon: "🥈",
  },
  {
    name: "gold",
    displayName: "Gold",
    minPoints: 25000,
    cashbackPercentage: 1.5,
    dailyLimit: 25000000,
    color: "#FFD700",
    icon: "🥇",
  },
  {
    name: "platinum",
    displayName: "Platinum",
    minPoints: 100000,
    cashbackPercentage: 2,
    dailyLimit: 50000000,
    color: "#E5E4E2",
    icon: "💎",
  },
  {
    name: "diamond",
    displayName: "Diamond",
    minPoints: 500000,
    cashbackPercentage: 3,
    dailyLimit: -1,
    color: "#B9F2FF",
    icon: "👑",
  },
]

// Mock User
export const mockUser: User = {
  id: "user-1",
  email: "john.doe@email.com",
  phone: "081234567890",
  fullName: "John Doe",
  username: "johndoe",
  avatar: "/professional-avatar.png",
  kycStatus: "verified",
  level: "gold",
  points: 45250,
  totalTransactions: 342,
  createdAt: new Date("2023-01-15"),
  settings: {
    twoFactorEnabled: true,
    biometricEnabled: true,
    pinEnabled: true,
    language: "id",
    notifications: { push: true, email: true, sms: false },
    dailyLimit: 25000000,
  },
}

// Mock Wallet
export const mockWallet: Wallet = {
  id: "wallet-1",
  userId: "user-1",
  balanceMain: 12500000,
  balanceMarket: 8750000,
  balanceSavings: 5000000,
  balancePoints: 45250,
  currency: "IDR",
}

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: "tx-1",
    userId: "user-1",
    type: "topup",
    amount: 500000,
    fee: 0,
    status: "success",
    description: "Top Up via BCA",
    createdAt: new Date("2024-12-28T10:30:00"),
  },
  {
    id: "tx-2",
    userId: "user-1",
    type: "transfer",
    amount: -150000,
    fee: 2500,
    status: "success",
    description: "Transfer ke @sarah",
    recipient: "sarah",
    createdAt: new Date("2024-12-28T09:15:00"),
  },
  {
    id: "tx-3",
    userId: "user-1",
    type: "food",
    amount: -85000,
    fee: 0,
    status: "success",
    description: "McDonald's - Big Mac Meal",
    createdAt: new Date("2024-12-27T19:45:00"),
  },
  {
    id: "tx-4",
    userId: "user-1",
    type: "pulsa",
    amount: -50000,
    fee: 1500,
    status: "success",
    description: "Pulsa Telkomsel 50.000",
    createdAt: new Date("2024-12-27T14:20:00"),
  },
  {
    id: "tx-5",
    userId: "user-1",
    type: "crypto",
    amount: -1000000,
    fee: 5000,
    status: "success",
    description: "Beli Bitcoin 0.00045 BTC",
    createdAt: new Date("2024-12-26T11:00:00"),
  },
  {
    id: "tx-6",
    userId: "user-1",
    type: "cashback",
    amount: 25000,
    fee: 0,
    status: "success",
    description: "Cashback transaksi Desember",
    createdAt: new Date("2024-12-26T00:00:00"),
  },
  {
    id: "tx-7",
    userId: "user-1",
    type: "bills",
    amount: -350000,
    fee: 2500,
    status: "success",
    description: "Listrik PLN - Des 2024",
    createdAt: new Date("2024-12-25T08:30:00"),
  },
  {
    id: "tx-8",
    userId: "user-1",
    type: "payment",
    amount: -275000,
    fee: 0,
    status: "success",
    description: "Pembayaran QRIS - Starbucks",
    createdAt: new Date("2024-12-24T16:00:00"),
  },
  {
    id: "tx-9",
    userId: "user-1",
    type: "reward",
    amount: 10000,
    fee: 0,
    status: "success",
    description: "Daily Login Reward",
    createdAt: new Date("2024-12-24T00:00:00"),
  },
  {
    id: "tx-10",
    userId: "user-1",
    type: "transfer",
    amount: 250000,
    fee: 0,
    status: "success",
    description: "Terima dari @mike",
    createdAt: new Date("2024-12-23T20:15:00"),
  },
]

// Mock Crypto Assets
export const mockCryptoAssets: CryptoAsset[] = [
  {
    id: "btc",
    symbol: "BTC",
    name: "Bitcoin",
    icon: "₿",
    price: 1650000000,
    change24h: 2.45,
    marketCap: 32000000000000000,
    volume24h: 890000000000000,
  },
  {
    id: "eth",
    symbol: "ETH",
    name: "Ethereum",
    icon: "Ξ",
    price: 55000000,
    change24h: -1.23,
    marketCap: 6600000000000000,
    volume24h: 320000000000000,
  },
  {
    id: "usdt",
    symbol: "USDT",
    name: "Tether",
    icon: "₮",
    price: 15850,
    change24h: 0.01,
    marketCap: 1400000000000000,
    volume24h: 980000000000000,
  },
  {
    id: "bnb",
    symbol: "BNB",
    name: "BNB",
    icon: "◈",
    price: 10500000,
    change24h: 3.67,
    marketCap: 1540000000000000,
    volume24h: 45000000000000,
  },
  {
    id: "sol",
    symbol: "SOL",
    name: "Solana",
    icon: "◎",
    price: 3100000,
    change24h: 5.82,
    marketCap: 1380000000000000,
    volume24h: 89000000000000,
  },
  {
    id: "xrp",
    symbol: "XRP",
    name: "Ripple",
    icon: "✕",
    price: 35000,
    change24h: -0.45,
    marketCap: 1900000000000000,
    volume24h: 67000000000000,
  },
]

// Mock Crypto Wallets
export const mockCryptoWallets: CryptoWallet[] = [
  {
    id: "cw-1",
    userId: "user-1",
    coinType: "BTC",
    balance: 0.00234,
    walletAddress: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    valueInIdr: 3861000,
  },
  {
    id: "cw-2",
    userId: "user-1",
    coinType: "ETH",
    balance: 0.5,
    walletAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f5b6f2",
    valueInIdr: 27500000,
  },
  {
    id: "cw-3",
    userId: "user-1",
    coinType: "USDT",
    balance: 150,
    walletAddress: "TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9",
    valueInIdr: 2377500,
  },
  {
    id: "cw-4",
    userId: "user-1",
    coinType: "SOL",
    balance: 2.5,
    walletAddress: "7EYnhQoR9YM3N7UoaKRoA44Uy8JeaZV3qyouov87awMs",
    valueInIdr: 7750000,
  },
]

// Mock Restaurants
export const mockRestaurants: Restaurant[] = [
  {
    id: "rest-1",
    name: "McDonald's",
    image: "/mcdonalds-restaurant.png",
    rating: 4.5,
    reviewCount: 2341,
    category: ["Fast Food", "Burgers"],
    priceLevel: 2,
    distance: 1.2,
    deliveryTime: "15-25 min",
    deliveryFee: 8000,
    isOpen: true,
    isFeatured: true,
  },
  {
    id: "rest-2",
    name: "Sate Khas Senayan",
    image: "/indonesian-satay-restaurant.jpg",
    rating: 4.7,
    reviewCount: 1823,
    category: ["Indonesian", "Satay"],
    priceLevel: 2,
    distance: 2.5,
    deliveryTime: "25-35 min",
    deliveryFee: 12000,
    isOpen: true,
    isFeatured: true,
  },
  {
    id: "rest-3",
    name: "Pizza Hut",
    image: "/pizza-hut-restaurant.jpg",
    rating: 4.3,
    reviewCount: 1567,
    category: ["Pizza", "Italian"],
    priceLevel: 2,
    distance: 1.8,
    deliveryTime: "30-40 min",
    deliveryFee: 10000,
    isOpen: true,
    isFeatured: false,
  },
  {
    id: "rest-4",
    name: "Warung Padang Sederhana",
    image: "/padang-food-restaurant.jpg",
    rating: 4.6,
    reviewCount: 987,
    category: ["Indonesian", "Padang"],
    priceLevel: 1,
    distance: 0.8,
    deliveryTime: "20-30 min",
    deliveryFee: 5000,
    isOpen: true,
    isFeatured: false,
  },
  {
    id: "rest-5",
    name: "Starbucks",
    image: "/bustling-coffee-shop.png",
    rating: 4.4,
    reviewCount: 3456,
    category: ["Coffee", "Cafe"],
    priceLevel: 3,
    distance: 0.5,
    deliveryTime: "10-20 min",
    deliveryFee: 8000,
    isOpen: true,
    isFeatured: true,
  },
  {
    id: "rest-6",
    name: "Bakso Lapangan Tembak",
    image: "/bakso-meatball-soup.jpg",
    rating: 4.8,
    reviewCount: 2134,
    category: ["Indonesian", "Soup"],
    priceLevel: 1,
    distance: 3.2,
    deliveryTime: "35-45 min",
    deliveryFee: 15000,
    isOpen: true,
    isFeatured: false,
  },
]

// Mock Menu Items
export const mockMenuItems: MenuItem[] = [
  {
    id: "menu-1",
    restaurantId: "rest-1",
    name: "Big Mac",
    description: "Two beef patties, special sauce, lettuce, cheese",
    image: "/big-mac-burger.jpg",
    price: 52000,
    category: "Burgers",
    isPopular: true,
    isAvailable: true,
  },
  {
    id: "menu-2",
    restaurantId: "rest-1",
    name: "McChicken",
    description: "Crispy chicken patty with mayo and lettuce",
    image: "/mcchicken-sandwich.jpg",
    price: 35000,
    category: "Burgers",
    isPopular: true,
    isAvailable: true,
  },
  {
    id: "menu-3",
    restaurantId: "rest-1",
    name: "Large Fries",
    description: "Golden crispy french fries",
    image: "/crispy-french-fries.png",
    price: 22000,
    category: "Sides",
    isPopular: false,
    isAvailable: true,
  },
  {
    id: "menu-4",
    restaurantId: "rest-1",
    name: "McFlurry Oreo",
    description: "Soft serve ice cream with Oreo pieces",
    image: "/mcflurry-oreo.jpg",
    price: 18000,
    category: "Desserts",
    isPopular: true,
    isAvailable: true,
  },
  {
    id: "menu-5",
    restaurantId: "rest-2",
    name: "Sate Ayam",
    description: "10 tusuk sate ayam dengan bumbu kacang",
    image: "/chicken-satay.jpg",
    price: 45000,
    category: "Main",
    isPopular: true,
    isAvailable: true,
  },
  {
    id: "menu-6",
    restaurantId: "rest-2",
    name: "Sate Kambing",
    description: "10 tusuk sate kambing muda",
    image: "/lamb-satay.jpg",
    price: 65000,
    category: "Main",
    isPopular: true,
    isAvailable: true,
  },
]

// Mock Badges
export const mockBadges: Badge[] = [
  {
    id: "badge-1",
    name: "Early Adopter",
    description: "Bergabung sejak awal peluncuran",
    icon: "🌟",
    category: "special",
    requirement: "Join dalam 30 hari pertama",
    isEarned: true,
    earnedAt: new Date("2023-01-15"),
  },
  {
    id: "badge-2",
    name: "Transaction Master",
    description: "Telah melakukan 1000 transaksi",
    icon: "💳",
    category: "transaction",
    requirement: "1000 transaksi",
    isEarned: false,
    progress: 342,
    maxProgress: 1000,
  },
  {
    id: "badge-3",
    name: "Crypto Trader",
    description: "Trading crypto aktif",
    icon: "📈",
    category: "crypto",
    requirement: "50 transaksi crypto",
    isEarned: true,
    earnedAt: new Date("2024-06-20"),
  },
  {
    id: "badge-4",
    name: "Food Hunter",
    description: "Pesan dari 50 restaurant berbeda",
    icon: "🍔",
    category: "food",
    requirement: "50 restaurant",
    isEarned: false,
    progress: 28,
    maxProgress: 50,
  },
  {
    id: "badge-5",
    name: "Savvy Shopper",
    description: "Kumpulkan 100.000 poin",
    icon: "🛒",
    category: "transaction",
    requirement: "100.000 poin",
    isEarned: false,
    progress: 45250,
    maxProgress: 100000,
  },
  {
    id: "badge-6",
    name: "Social Butterfly",
    description: "Ajak 10 teman bergabung",
    icon: "🦋",
    category: "social",
    requirement: "10 referral",
    isEarned: true,
    earnedAt: new Date("2024-03-10"),
  },
  {
    id: "badge-7",
    name: "Bill Payer",
    description: "Bayar 100 tagihan tepat waktu",
    icon: "📋",
    category: "transaction",
    requirement: "100 tagihan",
    isEarned: false,
    progress: 67,
    maxProgress: 100,
  },
  {
    id: "badge-8",
    name: "Diamond Hands",
    description: "Hold crypto selama 6 bulan",
    icon: "💎",
    category: "crypto",
    requirement: "Hold 6 bulan",
    isEarned: true,
    earnedAt: new Date("2024-07-15"),
  },
]

// Mock Missions
export const mockMissions: Mission[] = [
  {
    id: "mission-1",
    title: "Top Up Pertama Hari Ini",
    description: "Lakukan top up minimal Rp100.000",
    reward: 500,
    rewardType: "points",
    progress: 0,
    target: 1,
    expiresAt: new Date(new Date().setHours(23, 59, 59, 999)),
    isCompleted: false,
    isClaimed: false,
  },
  {
    id: "mission-2",
    title: "Transfer 3x",
    description: "Lakukan 3 kali transfer hari ini",
    reward: 1000,
    rewardType: "points",
    progress: 1,
    target: 3,
    expiresAt: new Date(new Date().setHours(23, 59, 59, 999)),
    isCompleted: false,
    isClaimed: false,
  },
  {
    id: "mission-3",
    title: "Pesan Makanan",
    description: "Pesan makanan dari restaurant manapun",
    reward: 5,
    rewardType: "cashback",
    progress: 0,
    target: 1,
    expiresAt: new Date(new Date().setHours(23, 59, 59, 999)),
    isCompleted: false,
    isClaimed: false,
  },
  {
    id: "mission-4",
    title: "Trade Crypto",
    description: "Lakukan 1 transaksi crypto",
    reward: 2000,
    rewardType: "points",
    progress: 0,
    target: 1,
    expiresAt: new Date(new Date().setHours(23, 59, 59, 999)),
    isCompleted: false,
    isClaimed: false,
  },
  {
    id: "mission-5",
    title: "Bayar Tagihan",
    description: "Bayar 1 tagihan apapun",
    reward: 750,
    rewardType: "points",
    progress: 0,
    target: 1,
    expiresAt: new Date(new Date().setHours(23, 59, 59, 999)),
    isCompleted: false,
    isClaimed: false,
  },
]

// Mock Leaderboard
export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "user-top-1",
    username: "cryptoking",
    avatar: "/diverse-group-avatars.png",
    points: 1250000,
    level: "diamond",
  },
  {
    rank: 2,
    userId: "user-top-2",
    username: "traderpro",
    avatar: "/pandora-ocean-scene.png",
    points: 980000,
    level: "diamond",
  },
  {
    rank: 3,
    userId: "user-top-3",
    username: "savvysaver",
    avatar: "/diverse-group-futuristic-setting.png",
    points: 756000,
    level: "platinum",
  },
  {
    rank: 4,
    userId: "user-top-4",
    username: "foodielove",
    avatar: "/diverse-group-futuristic-avatars.png",
    points: 520000,
    level: "platinum",
  },
  {
    rank: 5,
    userId: "user-top-5",
    username: "billmaster",
    avatar: "/diverse-futuristic-avatars.png",
    points: 445000,
    level: "gold",
  },
  {
    rank: 42,
    userId: "user-1",
    username: "johndoe",
    avatar: "/professional-avatar.png",
    points: 45250,
    level: "gold",
  },
]

// Mock Pulsa Providers
export const mockPulsaProviders: PulsaProvider[] = [
  {
    id: "telkomsel",
    name: "Telkomsel",
    icon: "/telkomsel-logo.png",
    prefix: ["0811", "0812", "0813", "0821", "0822", "0823", "0851", "0852", "0853"],
  },
  {
    id: "indosat",
    name: "Indosat Ooredoo",
    icon: "/indosat-logo.jpg",
    prefix: ["0814", "0815", "0816", "0855", "0856", "0857", "0858"],
  },
  {
    id: "xl",
    name: "XL Axiata",
    icon: "/xl-axiata-logo.png",
    prefix: ["0817", "0818", "0819", "0859", "0877", "0878"],
  },
  { id: "tri", name: "3 (Tri)", icon: "/tri-indonesia-logo.png", prefix: ["0895", "0896", "0897", "0898", "0899"] },
  {
    id: "smartfren",
    name: "Smartfren",
    icon: "/smartfren-logo.png",
    prefix: ["0881", "0882", "0883", "0884", "0885", "0886", "0887", "0888", "0889"],
  },
]

// Mock Pulsa Packages
export const mockPulsaPackages: PulsaPackage[] = [
  {
    id: "pkg-1",
    providerId: "telkomsel",
    name: "Pulsa 10.000",
    price: 11500,
    value: 10000,
    type: "pulsa",
    validity: "0 hari",
    description: "Pulsa reguler",
  },
  {
    id: "pkg-2",
    providerId: "telkomsel",
    name: "Pulsa 25.000",
    price: 26000,
    value: 25000,
    type: "pulsa",
    validity: "0 hari",
    description: "Pulsa reguler",
  },
  {
    id: "pkg-3",
    providerId: "telkomsel",
    name: "Pulsa 50.000",
    price: 51500,
    value: 50000,
    type: "pulsa",
    validity: "0 hari",
    description: "Pulsa reguler",
  },
  {
    id: "pkg-4",
    providerId: "telkomsel",
    name: "Pulsa 100.000",
    price: 101500,
    value: 100000,
    type: "pulsa",
    validity: "0 hari",
    description: "Pulsa reguler",
  },
  {
    id: "pkg-5",
    providerId: "telkomsel",
    name: "1GB 1 Hari",
    price: 12000,
    value: 1024,
    type: "data",
    validity: "1 hari",
    description: "Kuota internet 1GB",
  },
  {
    id: "pkg-6",
    providerId: "telkomsel",
    name: "3GB 7 Hari",
    price: 25000,
    value: 3072,
    type: "data",
    validity: "7 hari",
    description: "Kuota internet 3GB",
  },
  {
    id: "pkg-7",
    providerId: "telkomsel",
    name: "10GB 30 Hari",
    price: 65000,
    value: 10240,
    type: "data",
    validity: "30 hari",
    description: "Kuota internet 10GB",
  },
  {
    id: "pkg-8",
    providerId: "telkomsel",
    name: "25GB 30 Hari",
    price: 120000,
    value: 25600,
    type: "data",
    validity: "30 hari",
    description: "Kuota internet 25GB",
  },
]

// Mock Promos
export const mockPromos: Promo[] = [
  {
    id: "promo-1",
    title: "Cashback 50% Top Up",
    description: "Cashback hingga Rp25.000 untuk top up pertama",
    discount: 50,
    discountType: "percentage",
    minTransaction: 50000,
    maxDiscount: 25000,
    validUntil: new Date("2024-12-31"),
    category: ["topup"],
    image: "/cashback-promotion-banner.jpg",
  },
  {
    id: "promo-2",
    title: "Gratis Ongkir",
    description: "Gratis ongkir untuk pesanan makanan min. Rp50.000",
    discount: 15000,
    discountType: "fixed",
    minTransaction: 50000,
    validUntil: new Date("2024-12-31"),
    category: ["food"],
    image: "/free-delivery-promotion.png",
  },
  {
    id: "promo-3",
    title: "Double Points",
    description: "Poin 2x lipat untuk semua transaksi crypto",
    discount: 100,
    discountType: "percentage",
    minTransaction: 100000,
    validUntil: new Date("2024-12-30"),
    category: ["crypto"],
    image: "/crypto-trading-promotion.jpg",
  },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    title: "Transfer Berhasil",
    message: "Transfer Rp150.000 ke @sarah telah berhasil",
    type: "transaction",
    isRead: false,
    createdAt: new Date("2024-12-28T09:15:00"),
  },
  {
    id: "notif-2",
    userId: "user-1",
    title: "Promo Spesial!",
    message: "Dapatkan cashback 50% untuk top up hari ini",
    type: "promo",
    isRead: false,
    createdAt: new Date("2024-12-28T08:00:00"),
  },
  {
    id: "notif-3",
    userId: "user-1",
    title: "Login Baru Terdeteksi",
    message: "Akun Anda login dari perangkat baru di Jakarta",
    type: "security",
    isRead: true,
    createdAt: new Date("2024-12-27T20:30:00"),
  },
  {
    id: "notif-4",
    userId: "user-1",
    title: "Pesanan Dikirim",
    message: "Pesanan McDonald's sedang dalam perjalanan",
    type: "transaction",
    isRead: true,
    createdAt: new Date("2024-12-27T19:50:00"),
  },
]
